### ISSUE TITLE
Create `User` model

### ISSUE THREAD

**Issue by SprocketCreations** [SprocketCreations/truck-rental#5]
### With the keys:
- [ ] `email` VARCHAR NOT NULL verify is email
- [ ] `password` VARCHAR NOT NULL verify is not regex
### Hooks:
- [ ] create hook to hash the password with bcrypt
---
`not: /^(.{0,7}|[^0-9]*|[^A-Z]*|[^a-z]*|[a-zA-Z0-9]*)$/,`

**Comment by error201** [comment]
Completed.
