### ISSUE TITLE
Create `Truck` model

### ISSUE THREAD

**Issue by SprocketCreations** [SprocketCreations/truck-rental#6]
### With keys:
- [ ] `name` VARCHAR NN
- [ ] `image` VARCHAR NN
- [ ] `width` FLOAT NN
- [ ] `height` FLOAT NN
- [ ] `length` FLOAT NN
- [ ] `costPerMile` DECIMAL NN
- [ ] `costPerHour` DECIMAL NN
- [ ] `milesPerGallon` FLOAT NN
- [ ] `odometer` INT NN
- [ ] `fuelCapacity` FLOAT NN
- [ ] `features` TEXT

**Comment by error201** [comment]
Completed.
